version: '3'
services:
  mongoDB:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
  server:
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: inkling_server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    depends_on: 
      - mongoDB
    environment:
      NODE_ENV: ${NODE_ENV}
  client:
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: inkling_client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    depends_on: 
      - server
  
volumes:
  mongodb-data:

